[package]
name = "slots-example"
version = "0.1.0"
edition = "2021"

[dependencies]
rvue = { path = "../../rvue" }
rvue-macro = { path = "../../rvue-macro" }
rvue-style = { path = "../../rvue-style" }
rudo-gc.workspace = true