[workspace]
members = [
    "crates/rvue-signals",
    "crates/rvue",
    "crates/rvue-style",
    "crates/rvue-macro",
    "crates/rvue-examples/counter",
    "crates/rvue-examples/list",
    "crates/rvue-examples/layout",
    "crates/rvue-examples/benchmark",
    "crates/rvue-examples/form",
    "crates/rvue-examples/slots",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Rvue Contributors"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
rudo-gc = "0.2"

